data:
  path: "data/dataset.csv"
  target: "target_column"
  test_size: 0.2
  random_state: 42

preprocessing:
  scale: true
  encode_categorical: true

model:
  type: "logistic_regression"
  params:
    max_iter: 500

evaluation:
  metrics: ["accuracy", "f1_score"]
